"""add mobile tracking tables

Revision ID: c8f3a71d2e64
Revises: 7a9c2e4f1b68
Create Date: 2026-07-20
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "c8f3a71d2e64"
down_revision: Union[str, None] = "7a9c2e4f1b68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "mobile_tracking_subjects",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "subject_type",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "display_name",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "operator_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "phone_number",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "external_reference",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_by_operator_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["operators.id"],
            name=(
                "fk_mobile_tracking_subjects_"
                "operator_id_operators"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_operator_id"],
            ["operators.id"],
            name=(
                "fk_mobile_tracking_subjects_"
                "created_by_operator_id_operators"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_mobile_tracking_subjects",
        ),
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_subjects_id",
        "mobile_tracking_subjects",
        ["id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_subjects_subject_type",
        "mobile_tracking_subjects",
        ["subject_type"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_subjects_operator_id",
        "mobile_tracking_subjects",
        ["operator_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_subjects_phone_number",
        "mobile_tracking_subjects",
        ["phone_number"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_subjects_external_reference",
        "mobile_tracking_subjects",
        ["external_reference"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        (
            "ix_mobile_tracking_subjects_"
            "created_by_operator_id"
        ),
        "mobile_tracking_subjects",
        ["created_by_operator_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "mobile_devices",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "device_id",
            sa.String(length=150),
            nullable=False,
        ),
        sa.Column(
            "subject_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "device_name",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "platform",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "app_version",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "registered_by_operator_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["mobile_tracking_subjects.id"],
            name=(
                "fk_mobile_devices_subject_id_"
                "mobile_tracking_subjects"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_operator_id"],
            ["operators.id"],
            name=(
                "fk_mobile_devices_"
                "registered_by_operator_id_operators"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_mobile_devices",
        ),
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_devices_id",
        "mobile_devices",
        ["id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_devices_device_id",
        "mobile_devices",
        ["device_id"],
        unique=True,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_devices_subject_id",
        "mobile_devices",
        ["subject_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_devices_status",
        "mobile_devices",
        ["status"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        (
            "ix_mobile_devices_"
            "registered_by_operator_id"
        ),
        "mobile_devices",
        ["registered_by_operator_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "mobile_tracking_sessions",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "subject_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "device_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "session_type",
            sa.String(length=30),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "case_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "consent_given_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "consent_reference",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "consent_revoked_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "expected_end_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "ended_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "started_by_operator_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "ended_by_operator_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["mobile_tracking_subjects.id"],
            name=(
                "fk_mobile_tracking_sessions_subject_id_"
                "mobile_tracking_subjects"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["mobile_devices.id"],
            name=(
                "fk_mobile_tracking_sessions_"
                "device_id_mobile_devices"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["case_files.id"],
            name=(
                "fk_mobile_tracking_sessions_"
                "case_id_case_files"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["started_by_operator_id"],
            ["operators.id"],
            name=(
                "fk_mobile_tracking_sessions_"
                "started_by_operator_id_operators"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ended_by_operator_id"],
            ["operators.id"],
            name=(
                "fk_mobile_tracking_sessions_"
                "ended_by_operator_id_operators"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_mobile_tracking_sessions",
        ),
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_sessions_id",
        "mobile_tracking_sessions",
        ["id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_sessions_subject_id",
        "mobile_tracking_sessions",
        ["subject_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_sessions_device_id",
        "mobile_tracking_sessions",
        ["device_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_sessions_session_type",
        "mobile_tracking_sessions",
        ["session_type"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_sessions_status",
        "mobile_tracking_sessions",
        ["status"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_tracking_sessions_case_id",
        "mobile_tracking_sessions",
        ["case_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        (
            "ix_mobile_tracking_sessions_"
            "started_by_operator_id"
        ),
        "mobile_tracking_sessions",
        ["started_by_operator_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        (
            "ix_mobile_tracking_sessions_"
            "ended_by_operator_id"
        ),
        "mobile_tracking_sessions",
        ["ended_by_operator_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "mobile_location_logs",
        sa.Column(
            "id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "session_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "subject_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "device_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "latitude",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "accuracy_metres",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "altitude_metres",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "speed_kmh",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "heading_degrees",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "battery_percentage",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["mobile_tracking_sessions.id"],
            name=(
                "fk_mobile_location_logs_session_id_"
                "mobile_tracking_sessions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["mobile_tracking_subjects.id"],
            name=(
                "fk_mobile_location_logs_subject_id_"
                "mobile_tracking_subjects"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["mobile_devices.id"],
            name=(
                "fk_mobile_location_logs_device_id_"
                "mobile_devices"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_mobile_location_logs",
        ),
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_location_logs_session_id",
        "mobile_location_logs",
        ["session_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_location_logs_subject_id",
        "mobile_location_logs",
        ["subject_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_location_logs_device_id",
        "mobile_location_logs",
        ["device_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_location_logs_recorded_at",
        "mobile_location_logs",
        ["recorded_at"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_location_logs_received_at",
        "mobile_location_logs",
        ["received_at"],
        unique=False,
        if_not_exists=True,
    )

    op.create_table(
        "mobile_sos_alerts",
        sa.Column(
            "id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "subject_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "device_id",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
        ),
        sa.Column(
            "latitude",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "accuracy_metres",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "message",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "triggered_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "acknowledged_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "acknowledged_by_operator_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "resolved_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "resolved_by_operator_id",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["mobile_tracking_sessions.id"],
            name=(
                "fk_mobile_sos_alerts_session_id_"
                "mobile_tracking_sessions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["mobile_tracking_subjects.id"],
            name=(
                "fk_mobile_sos_alerts_subject_id_"
                "mobile_tracking_subjects"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["mobile_devices.id"],
            name=(
                "fk_mobile_sos_alerts_device_id_"
                "mobile_devices"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by_operator_id"],
            ["operators.id"],
            name=(
                "fk_mobile_sos_alerts_"
                "acknowledged_by_operator_id_operators"
            ),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_operator_id"],
            ["operators.id"],
            name=(
                "fk_mobile_sos_alerts_"
                "resolved_by_operator_id_operators"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name="pk_mobile_sos_alerts",
        ),
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_sos_alerts_id",
        "mobile_sos_alerts",
        ["id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_sos_alerts_session_id",
        "mobile_sos_alerts",
        ["session_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_sos_alerts_subject_id",
        "mobile_sos_alerts",
        ["subject_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_sos_alerts_device_id",
        "mobile_sos_alerts",
        ["device_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_sos_alerts_status",
        "mobile_sos_alerts",
        ["status"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        "ix_mobile_sos_alerts_triggered_at",
        "mobile_sos_alerts",
        ["triggered_at"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        (
            "ix_mobile_sos_alerts_"
            "acknowledged_by_operator_id"
        ),
        "mobile_sos_alerts",
        ["acknowledged_by_operator_id"],
        unique=False,
        if_not_exists=True,
    )

    op.create_index(
        (
            "ix_mobile_sos_alerts_"
            "resolved_by_operator_id"
        ),
        "mobile_sos_alerts",
        ["resolved_by_operator_id"],
        unique=False,
        if_not_exists=True,
    )


def downgrade() -> None:
    op.drop_table(
        "mobile_sos_alerts",
        if_exists=True,
    )

    op.drop_table(
        "mobile_location_logs",
        if_exists=True,
    )

    op.drop_table(
        "mobile_tracking_sessions",
        if_exists=True,
    )

    op.drop_table(
        "mobile_devices",
        if_exists=True,
    )

    op.drop_table(
        "mobile_tracking_subjects",
        if_exists=True,
    )